# Generated by Django 3.2.5 on 2022-02-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_internal_id', models.IntegerField()),
                ('anime_anilist_id', models.IntegerField()),
            ],
        ),
    ]
